### ISSUE TITLE
--extra-param option continually failing with Unknown field error

### ISSUE THREAD

**Issue by apat00** [chef-partners/knife-vrealize#11]
Sincere apologies, I'm totally new to this so will no doubt be making lots of mistakes, but I thought I'd try logging an issue on the off chance you could help. I'm trying to get the knife-vrealize plugin working on our estate to allow us to generate server build requests from the command line. We've got VMware guys in to configure vRealize and I'm able to connect to their test vRA deployment ok. Catalog list works fine and I'm able to submit a server create request but get an error saying that the environment isn't set properly:

> knife vra server create xxxxx --cpus 1 --memory 4096 --notes 'test API build' --ssh-password 'xxxxx' --requested-for xxxx@xxxx.xxxx.xxx --vra-disable-ssl-verify --subtenant-id xxxxxx
Catalog request xxxxx submitted.
Waiting for request to complete.
Current request status: PENDING_PRE_APPROVAL.
Current request status: IN_PROGRESS.
Catalog request complete.

Request Status: FAILED
Completion State: FAILED
Completion Details: Unknown environment specified from request form (Dynamic Script Module name : calculateNetworkPathName#50)

FATAL: Unknown environment specified from request form (Dynamic Script Module name : calculateNetworkPathName#50)

When I try to use the --extra-param option to set the additional fields I keep getting:

> knife vra server create xxxxx --cpus 1 --memory 4096 --notes 'test API build' --ssh-password 'xxxx' --requested-for xxxxx@xxxx.xxxxx.xxx --vra-disable-ssl-verify --subtenant-id xxxxx --extra-param jsEnvironment=string:Development
ERROR: Vra::Exception::RequestError: Unable to submit request: Unknown field: jsEnvironment

I'm being assured by the VMWare guys that the field name I need to set are:
jsEnvironment
jsBusinessApplication
jsServerRole
jsStorageTier

but when I try providing them in the extra-param option it always comes back as unknown. 

Any suggestions? I'm assuming it's a problem with the VMware side, and they've just given me the wrong param names, but thought I would ask in case this is a known issue with the plugin. 
Regarding the plugin I downloaded version 1.4.0 on the 5th of Nov so I'm on the latest version I know of. (I saw the earlier update that related to the --extra-param bug, but it looks like my copy has the fix applied.)

**Comment by adamleff** [comment]
@apat00 The vRA API is a bit finicky, unfortunately. It requires you to know a bit more than the casual user about how some of the functions of vRA are actually implemented.

Can you try and prefix your field name with `provider-` and see if that works?

`--extra-param provider-jsEnvironment=string:Development`

**Comment by apat00** [comment]
Really can't thank you enough for such a speedy and accurate resolution to my problem. I've emailed the onsite VMware guys a number of time on this subject without getting anywhere, prefixing provider- means all the additional options are now being picked up without issue. 
Unfortunately I'm now getting another error :)
"Cannot locate a unique blueprint within the IaaS database that matches the blueprint name provided"
but this is definitely on the vRealize side so will progress with VMware. A huge thank you once again..!

**Comment by adamleff** [comment]
@apat00 You're so welcome!  Thanks for using the plugin!
