### ISSUE TITLE
Provide a --noboostrap option

### ISSUE THREAD

**Issue by thenoid** [chef-partners/knife-vrealize#15]
wondering if it'd be possible to request a "no bootstrap" option?   As a user sometimes i just want to carve a node without bootstraping it, either for debuging or perhaps the chef boot strapping is handle via another method (such as the chef VRO plugin https://solutionexchange.vmware.com/store/products/chef-plugin-for-vrealize-orchestrator)

**Comment by adamleff** [comment]
knife-vrealize (and many other knife plugins for cloud integrations) use [knife-cloud](https://github.com/chef/knife-cloud) under the covers, and knife-cloud actually handles the bootstrapping. I'd recommend logging an issue on that repo, or even better, submitting a PR to add the behavior. :)
