### ISSUE TITLE
certificate verify failure

### ISSUE THREAD

**Issue by jcarapet** [chef-partners/knife-vrealize#16]
I think this might be human error, but wanted to make sure. 

trying to connect to my vra instance but continually getting error 
`Original Exception: OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed`

I have tried adding `knife[:vra_verify_ssl] = false` to my knife.rb, and removed https from `knife[:vra_base_url]` but that just leads to another error. 

knife ssl check doesn't show and error, and a fetch doesn't seem to have any issue.

My best guess is that since we have different ssl certs on chef-server than VRA instance it isn't matching up and causing errors. If they need to match, please let me know. 

I am somewhat grasping at straws, so if you need more information I will be happy to provide.

**Comment by adamleff** [comment]
Hi, @jcarapet.

The parameter you want to set in your `knife.rb` is:

```
knife[:vra_disable_ssl_verify] = true
```

... or pass `--vra-disable-ssl-verify` on the command line.

The code that grabs this setting is here:

https://github.com/chef-partners/knife-vrealize/blob/master/lib/chef/knife/cloud/vra_service_options.rb#L38-L42

... and the code that consumes this setting is here:

https://github.com/chef-partners/knife-vrealize/blob/master/lib/chef/knife/cloud/vra_service.rb#L37
https://github.com/chef-partners/knife-vrealize/blob/master/lib/chef/knife/cloud/vra_service.rb#L48
https://github.com/chef-partners/knife-vrealize/blob/master/lib/chef/knife/cloud/vra_service_helpers.rb#L36-L38

You also likely need to keep the `https` in your `vra_base_url` as vRA expects the connection to be SSL.

Hope that helps! If not, please reopen this issue for additional assistance.

~Adam

**Comment by jcarapet** [comment]
I adjusted it to :vra_disable_ssl_verify in the knife.rb. This did not change the output. I then passed in the disable via the command line. I also passed in all values like username, password, and base_url in as command line arguments to see if that would help, but it still comes with the same output.

```jcarap0915mac:acx-nodejs jcarap$ knife vra catalog list --vra-username username@url --vra-password password --vra-base-url https://url.corp.company.net --vra-disable-ssl-verify true
ERROR: Could not establish a secure connection to the server.
Use `knife ssl check` to troubleshoot your SSL configuration.
If your Chef Server uses a self-signed certificate, you can use
`knife ssl fetch` to make knife trust the server's certificates.

Original Exception: OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed
```

You were correct that it needs to be https in the base_url or else it will fail with another error.

At this point, I think it's related to my ssl certs differing between chef server and vra server, but not sure why that would have affect. I will try to come up with some more information before officially reopening. 

As a point, I am getting the same behavior when trying to run kitchen-vra, so I bet it's a similar issue with my setup. if you can think of anything great, but I will post to this issue when I find a solution.

**Comment by adamleff** [comment]
The certs do not have to match. In fact, it's probably be bad if they did :)

Can you post the full output (with sensitive info redacted) of your knife command with `-VV` added to the command line? This should give us more debug output.

**Comment by jcarapet** [comment]
Certainly. I will do one with arguments passed and a base command.

# Command with arguments passed in
`jcarap0915mac:~ jcarap$ knife vra catalog list --user username --vra-password shupershecret --vra-base-url https://domain.subdomain.whatever.net --vra-disable-ssl-verify true -VV
INFO: Using configuration from /Users/jcarap/.chef/knife.rb
/opt/chefdk/embedded/lib/ruby/2.1.0/net/http.rb:923:in `connect': SSL_connect returned=1 errno=0 state=error: certificate verify failed (OpenSSL::SSL::SSLError)
	from /opt/chefdk/embedded/lib/ruby/2.1.0/net/http.rb:923:in `block in connect'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/timeout.rb:75:in `timeout'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/net/http.rb:923:in `connect'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/net/http.rb:852:in `start'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/net/http.rb:583:in `start'
	from /Users/jcarap/.chefdk/gem/ruby/2.1.0/gems/vmware-vra-1.6.1/lib/vra/http.rb:39:in `call'
	from /Users/jcarap/.chefdk/gem/ruby/2.1.0/gems/vmware-vra-1.6.1/lib/vra/http.rb:7:in `execute'
	from /Users/jcarap/.chefdk/gem/ruby/2.1.0/gems/vmware-vra-1.6.1/lib/vra/client.rb:172:in `http_post'
	from /Users/jcarap/.chefdk/gem/ruby/2.1.0/gems/vmware-vra-1.6.1/lib/vra/client.rb:103:in `generate_bearer_token'
	from /Users/jcarap/.chefdk/gem/ruby/2.1.0/gems/vmware-vra-1.6.1/lib/vra/client.rb:87:in `authorize!'
	from /Users/jcarap/.chefdk/gem/ruby/2.1.0/gems/vmware-vra-1.6.1/lib/vra/client.rb:118:in `http_fetch'
	from /Users/jcarap/.chefdk/gem/ruby/2.1.0/gems/vmware-vra-1.6.1/lib/vra/client.rb:135:in `http_get'
	from /Users/jcarap/.chefdk/gem/ruby/2.1.0/gems/vmware-vra-1.6.1/lib/vra/client.rb:139:in `http_get!'
	from /Users/jcarap/.chefdk/gem/ruby/2.1.0/gems/vmware-vra-1.6.1/lib/vra/client.rb:144:in `get_parsed'
	from /Users/jcarap/.chefdk/gem/ruby/2.1.0/gems/vmware-vra-1.6.1/lib/vra/client.rb:153:in `block in http_get_paginated_array!'
	from /Users/jcarap/.chefdk/gem/ruby/2.1.0/gems/vmware-vra-1.6.1/lib/vra/client.rb:152:in `loop'
	from /Users/jcarap/.chefdk/gem/ruby/2.1.0/gems/vmware-vra-1.6.1/lib/vra/client.rb:152:in `http_get_paginated_array!'
	from /Users/jcarap/.chefdk/gem/ruby/2.1.0/gems/vmware-vra-1.6.1/lib/vra/catalog.rb:28:in `all_items'
	from /Users/jcarap/.chefdk/gem/ruby/2.1.0/gems/knife-vrealize-1.4.0/lib/chef/knife/cloud/vra_service.rb:95:in `list_catalog_items'
	from /Users/jcarap/.chefdk/gem/ruby/2.1.0/gems/knife-vrealize-1.4.0/lib/chef/knife/vra_catalog_list.rb:53:in `query_resource'
	from /Users/jcarap/.chefdk/gem/ruby/2.1.0/gems/knife-cloud-1.2.1/lib/chef/knife/cloud/list_resource_command.rb:35:in `execute_command'
	from /Users/jcarap/.chefdk/gem/ruby/2.1.0/gems/knife-cloud-1.2.1/lib/chef/knife/cloud/command.rb:51:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/knife.rb:421:in `block in run_with_pretty_exceptions'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/local_mode.rb:44:in `with_server_connectivity'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/knife.rb:420:in `run_with_pretty_exceptions'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/knife.rb:219:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/application/knife.rb:148:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/bin/knife:25:in `<top (required)>'
	from /opt/chefdk/bin/knife:51:in `load'
	from /opt/chefdk/bin/knife:51:in `<main>'
`
# 
`knife vra catalog list -VV
INFO: Using configuration from /Users/jcarap/.chef/knife.rb
/opt/chefdk/embedded/lib/ruby/2.1.0/net/http.rb:923:in `connect': SSL_connect returned=1 errno=0 state=error: certificate verify failed (OpenSSL::SSL::SSLError)
	from /opt/chefdk/embedded/lib/ruby/2.1.0/net/http.rb:923:in `block in connect'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/timeout.rb:75:in `timeout'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/net/http.rb:923:in `connect'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/net/http.rb:852:in `start'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/net/http.rb:583:in `start'
	from /Users/jcarap/.chefdk/gem/ruby/2.1.0/gems/vmware-vra-1.6.1/lib/vra/http.rb:39:in `call'
	from /Users/jcarap/.chefdk/gem/ruby/2.1.0/gems/vmware-vra-1.6.1/lib/vra/http.rb:7:in `execute'
	from /Users/jcarap/.chefdk/gem/ruby/2.1.0/gems/vmware-vra-1.6.1/lib/vra/client.rb:172:in `http_post'
	from /Users/jcarap/.chefdk/gem/ruby/2.1.0/gems/vmware-vra-1.6.1/lib/vra/client.rb:103:in `generate_bearer_token'
	from /Users/jcarap/.chefdk/gem/ruby/2.1.0/gems/vmware-vra-1.6.1/lib/vra/client.rb:87:in `authorize!'
	from /Users/jcarap/.chefdk/gem/ruby/2.1.0/gems/vmware-vra-1.6.1/lib/vra/client.rb:118:in `http_fetch'
	from /Users/jcarap/.chefdk/gem/ruby/2.1.0/gems/vmware-vra-1.6.1/lib/vra/client.rb:135:in `http_get'
	from /Users/jcarap/.chefdk/gem/ruby/2.1.0/gems/vmware-vra-1.6.1/lib/vra/client.rb:139:in `http_get!'
	from /Users/jcarap/.chefdk/gem/ruby/2.1.0/gems/vmware-vra-1.6.1/lib/vra/client.rb:144:in `get_parsed'
	from /Users/jcarap/.chefdk/gem/ruby/2.1.0/gems/vmware-vra-1.6.1/lib/vra/client.rb:153:in `block in http_get_paginated_array!'
	from /Users/jcarap/.chefdk/gem/ruby/2.1.0/gems/vmware-vra-1.6.1/lib/vra/client.rb:152:in `loop'
	from /Users/jcarap/.chefdk/gem/ruby/2.1.0/gems/vmware-vra-1.6.1/lib/vra/client.rb:152:in `http_get_paginated_array!'
	from /Users/jcarap/.chefdk/gem/ruby/2.1.0/gems/vmware-vra-1.6.1/lib/vra/catalog.rb:28:in `all_items'
	from /Users/jcarap/.chefdk/gem/ruby/2.1.0/gems/knife-vrealize-1.4.0/lib/chef/knife/cloud/vra_service.rb:95:in `list_catalog_items'
	from /Users/jcarap/.chefdk/gem/ruby/2.1.0/gems/knife-vrealize-1.4.0/lib/chef/knife/vra_catalog_list.rb:53:in `query_resource'
	from /Users/jcarap/.chefdk/gem/ruby/2.1.0/gems/knife-cloud-1.2.1/lib/chef/knife/cloud/list_resource_command.rb:35:in `execute_command'
	from /Users/jcarap/.chefdk/gem/ruby/2.1.0/gems/knife-cloud-1.2.1/lib/chef/knife/cloud/command.rb:51:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/knife.rb:421:in `block in run_with_pretty_exceptions'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/local_mode.rb:44:in `with_server_connectivity'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/knife.rb:420:in `run_with_pretty_exceptions'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/knife.rb:219:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/application/knife.rb:148:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/bin/knife:25:in `<top (required)>'
	from /opt/chefdk/bin/knife:51:in `load'
	from /opt/chefdk/bin/knife:51:in `<main>'`

For fun, I will show a vro command that has the same issue. 
`knife vro workflow execute "Jeff Adds A New Environment" -VV
INFO: Using configuration from /Users/jcarap/.chef/knife.rb
Starting workflow execution...
ERROR: The workflow execution request failed: SSL_connect returned=1 errno=0 state=error: certificate verify failed
/Users/jcarap/.chefdk/gem/ruby/2.1.0/gems/rest-client-1.8.0/lib/restclient/request.rb:445:in `rescue in transmit': SSL_connect returned=1 errno=0 state=error: certificate verify failed (RestClient::SSLCertificateNotVerified)
	from /Users/jcarap/.chefdk/gem/ruby/2.1.0/gems/rest-client-1.8.0/lib/restclient/request.rb:350:in `transmit'
	from /Users/jcarap/.chefdk/gem/ruby/2.1.0/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in `execute'
	from /Users/jcarap/.chefdk/gem/ruby/2.1.0/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
	from /Users/jcarap/.chefdk/gem/ruby/2.1.0/gems/rest-client-1.8.0/lib/restclient/resource.rb:51:in `get'
	from /Users/jcarap/.chefdk/gem/ruby/2.1.0/gems/vcoworkflows-0.2.1/lib/vcoworkflows/vcosession.rb:56:in `get'
	from /Users/jcarap/.chefdk/gem/ruby/2.1.0/gems/vcoworkflows-0.2.1/lib/vcoworkflows/workflowservice.rb:47:in `get_workflow_for_name'
	from /Users/jcarap/.chefdk/gem/ruby/2.1.0/gems/vcoworkflows-0.2.1/lib/vcoworkflows/workflow.rb:131:in `initialize'
	from /Users/jcarap/.chefdk/gem/ruby/2.1.0/gems/knife-vrealize-1.4.0/lib/chef/knife/vro_workflow_execute.rb:74:in `new'
	from /Users/jcarap/.chefdk/gem/ruby/2.1.0/gems/knife-vrealize-1.4.0/lib/chef/knife/vro_workflow_execute.rb:74:in `vro_client'
	from /Users/jcarap/.chefdk/gem/ruby/2.1.0/gems/knife-vrealize-1.4.0/lib/chef/knife/vro_workflow_execute.rb:95:in `execute_workflow'
	from /Users/jcarap/.chefdk/gem/ruby/2.1.0/gems/knife-vrealize-1.4.0/lib/chef/knife/vro_workflow_execute.rb:174:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/knife.rb:421:in `block in run_with_pretty_exceptions'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/local_mode.rb:44:in `with_server_connectivity'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/knife.rb:420:in `run_with_pretty_exceptions'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/knife.rb:219:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/application/knife.rb:148:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/bin/knife:25:in `<top (required)>'
	from /opt/chefdk/bin/knife:51:in `load'
	from /opt/chefdk/bin/knife:51:in `<main>'`

**Comment by jcarapet** [comment]
small update on our end. After working with some of chef team, the problems persisted. Steps to fix were. 
knife ssl fetch and check, 
disable ssl_verify again with command line flag and in knife.rb
adjust all tuneable parameters
run `bundle exec knife vra catalog list` on cloned repo
test by passing direct values in with pry 
run tests using the vmware-vra gem to make direct api calls with our credentials (did this on workstation and spun up clean test vm as well)

each one ends up with the ssl_verify issue error message, even with turning off the flag. This is odd also because ssl has the green lock when hitting our vmware setup. Confirmed by JJ watching on working session.

**Comment by digitaljedi2** [comment]
This is happening for me as well. 
knife[:vra_disable_ssl_verify] = true is set in my knife.rb but I keep getting blocked by knife ssl check errors

**Comment by jdivine** [comment]
Pretty sure this is related to: https://github.com/chef-partners/vmware-vra-gem/issues/30

**Comment by jjasghar** [comment]
Yep i'm betting https://github.com/chef-partners/vmware-vra-gem/pull/31 this will fix it.

**Comment by jcarapet** [comment]
pulled in vmware-vra gem (1.7.0) and can now run knife-vrealize with the disable command. closing this issue.

**Comment by cstewart87** [comment]
It would be great to add this (`knife[:vra_disable_ssl_verify]`) to the docs :).  I just came across this and couldn't figure out why `knife[:verify_ssl]` was not being passed correctly.  All good now, thanks to this thread!

**Comment by jjasghar** [comment]
🤦‍♂️ I thought i had it already. I'll make the change right now.

**Comment by jjasghar** [comment]
@cstewart87 https://github.com/chef-partners/knife-vrealize/commit/5c2ac8d8c70707f7b82e405327d45f8005dd08ce

**Comment by cstewart87** [comment]
Awesome, thanks @jjasghar!  If I come across anything else I'll be sure to share 😄
