### ISSUE TITLE
knife[:vra_base_url] causes an error if URL has a trailing slash

### ISSUE THREAD

**Issue by vinyar** [chef-partners/knife-vrealize#24]
The resulting error is 'HTTPNotFound'
Removing trailing slash fixes the issue.

Expectation:
Presence of trailing slash makes no difference.

bad:
`knife[:vra_base_url] = 'https://vra.corp.local/'`

good:
`knife[:vra_base_url] = 'https://vra.corp.local'`

**Comment by vinyar** [comment]
Would this work:

```
         includer.class_eval do
            option :vra_base_url,
              long:        '--vra-base-url API_URL',
              description: 'URL for the vRA server',
              proc:        proc { |url| url.sub(/(\/)+$/,'') }
```

**Comment by jjasghar** [comment]
This seems pretty reasonable. I'd have to verify it on a vRA instance though. Can you put a PR in for the change?
