### ISSUE TITLE
Driver doesn't appear to support windows yet

### ISSUE THREAD

**Issue by mcascone** [chef-partners/knife-vrealize#29]
### Versions:

* Version of knife-vrealize: `knife-vrealize (2.1.0)`
* Version of chef:
`Chef Development Kit Version: 1.2.22`
`chef-client version: 12.18.31`

### Platform Details

* Version of vRA:  `version 7.0.1 (build 3621464)`
* Version of vRO:
* Version of ESXi:

### Scenario:

spin a windows server in vRa with knife.

### Steps to Reproduce:

called `knife vra server create` without specifying `--ssh-password`, as I am attempting to spin a windows catalog item.

### Expected Result:

I don't get asked for an ssh password.

### Actual Result:

I am required to provide `--ssh-password` even though I am spinning a windows machine.

```powershell
~ [master ≡]>  knife vra server create 'my-windows-catalog-id'  --winrm-password 'mypassword'
ERROR: You must provide either Identity file or SSH Password.
```

**Comment by mcascone** [comment]
once i got it to make the request, it appears `knife` is assuming the image is linux, which kinda explains why it wants an ssh-password:

```powershell
Waiting For vRA to collect the IPWaiting For vRA to collect the IPIP Addresses: 10.12.235.96
Status: ACTIVE
Owner IDs: mcascone@consilio.com
Owner Names: Max Cascone
Waiting For vRA to collect the IPBootstrapping the server by using bootstrap_protocol: ssh and image_os_type: linux
```

**Comment by mcascone** [comment]
I tried passing `--image-os-type windows`, same result.

**Comment by mcascone** [comment]
Ok. Never mind. I finally set `--bootstrap-protocol`, and it's functioning as expected. My misunderstanding!

**Comment by jjasghar** [comment]
@mcascone any chance you have a suggestion to make the docs better? If this wasn't clear it would be greate to update the README :)

**Comment by mcascone** [comment]
I'd love to, thanks!

Thanks, Max
